boostingMR/models/__init__.py
# -*- encoding:utf-8 -*-
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

boostingMR/models/attribute.py
# -*- encoding:utf-8 -*-
from boostingMR.models import db

class Attribute(db.Model) :
    __tablename__ = 'attribute'

    id = db.Column(db.Integer, primary_key=True)
    did = db.Column(db.Integer)
    name = db.Column(db.String)
    type = db.Column(db.Integer)
    isClass = db.Column(db.Integer, default=0)
    extra = db.Column(db.String)


    def __init__(self, did, name, type=0, isClass=0, extra=''):
        self.did = did
        self.name = name
        self.type = type
        self.isClass = isClass
        self.extra = extra

boostingMR/models/dataset.py
# -*- encoding:utf-8 -*-
from boostingMR.models import db

class Dataset(db.Model) :
    __tablename__ = 'dataset'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    size = db.Column(db.Integer, default=0)
    instanceNum = db.Column(db.Integer)
    attributeNum = db.Column(db.Integer)
    classNum = db.Column(db.Integer)
    classes = db.Column(db.String)
    description = db.Column(db.String)
    extra = db.Column(db.String)

    def __init__(self, name, instanceNum, attributeNum, classNum, classes='', description='', extra=''):
        self.name = name
        self.instanceNum = instanceNum
        self.attributeNum = attributeNum
        self.classNum = classNum
        self.description = description
        self.extra = extra

        if classes == '':
            self.classes = ','.join(['c'+str(i) for i in range(classNum)])
        else:
            self.classes = classes

    def setSize(size):
        self.size = size

    def getReadableSize():
        pass

    def getPathName(self):
        return self.name.replace(' ','_')

    def getClassNum(self):
        return self.classNum

    def getAttributeNum(self):
        return self.attributeNum

    def getInstanceNum(self):
        return self.instanceNum

boostingMR/__init__.py
# -*- encoding:utf-8 -*-
from flask import Flask
from boostingMR.lib.hadoop import init_hadoop
from boostingMR.views import init_views
import settings

app = Flask(__name__)
app.config.from_object(settings)

# init views
init_views(app)


init_hadoop(app)

boostingMR/lib/hadoop/__init__.py
# -*- encoding:utf-8 -*-
from pigpy.hadoop import Hadoop

hadoop = None

def init_hadoop(app):
    local_home = app.config['HADOOP_DIR']
    name_node = app.config['HADOOP_NAMENODE']
    classpaths = app.config['HADOOP_CLASSPATH']

    global hadoop
    hadoop = Hadoop(local_home, name_node, classpaths)

def get_hadoop():
    return hadoop

boostingMR/views/__init__.py
# -*- encoding:utf-8 -*-
from .frontend import frontend
from .datasets import datasets
from .training import training
from .testing import testing

def init_views(app):
    # register view models
    app.register_blueprint(frontend)
    app.register_blueprint(datasets)
    app.register_blueprint(training)
    app.register_blueprint(testing)

boostingMR/views/datasets.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template, url_for, redirect, request
from boostingMR.lib.hadoop.datactl import gen_random_data
from boostingMR.models.dataset import Dataset

datasets = Blueprint('datasets', __name__)

@datasets.route('/datasets')
def index():
    d = {}
    return render_template('datasets/index.html', **d)


@datasets.route('/datasets/random', methods=['POST', 'GET'])
def random():
    if request.method == 'GET':
        d = {}
        return render_template('datasets/random.html', **d)
    else:
        name = request.form['rdname']
        generator = request.form['rdgen']
        attributeNum = int(request.form['rdnAttr'])
        classNum = int(request.form['rdnClass'])
        instanceNum = int(request.form['rdnInst'])

        d = {}
        d['msg'] = 'test'

        dataset = Dataset(name, instanceNum, attributeNum, classNum)
        gen_random_data(dataset)
        
        return render_template('datasets/random.html', **d)

@datasets.route('/datasets/upload', methods=['POST', 'GET'])
def upload():
    if request.method == 'GET':
        d = {}
        return render_template('datasets/upload.html', **d)
    else:
        name = request.form['rdname']
        generator = request.form['rdgen']
        attributeNum = request.form['rdnAttr']
        classNum = request.form['rdnClass']
        instanceNum = request.form['rdnInst']

        d = {}
        d['msg'] = 'test'
        return render_template('datasets/random.html', **d)

boostingMR/views/frontend.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template, url_for, redirect

frontend = Blueprint('frontend', __name__)

@frontend.route('/')
def index():
    return render_template('/frontend.html')

@frontend.route('/dataset')
def dataset():
    return render_template('/dataset.html')

@frontend.route('/dataset', methods=['POST'])
def dataset_next():
    return redirect(url_for('frontend.model'))

@frontend.route('/model')
def model():
    return render_template('/model.html')

@frontend.route('/test')
def test():
    return render_template('/test.html')

boostingMR/views/testing.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template, url_for, redirect

testing = Blueprint('testing', __name__)

@testing.route('/testing')
def index():
    return render_template('testing/index.html')

boostingMR/views/training.py
# -*- encoding:utf-8 -*-
from flask import Blueprint, render_template, url_for, redirect

training = Blueprint('training', __name__)

@training.route('/training')
def index():
    return render_template('training/index.html')

boostingMR/templates/_layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>BoostingMR</title>
    <link href="/static/style.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
	<div id="hleft">
	  <h1>BoostingMR</h1>
	  <p>Scalable and Parallel Boosting with MapReduce</p>
	</div>
	<div id="hright">
	  <a href="{{url_for('frontend.index')}}" class="navb">Home</a>
	  <a href="{{url_for('datasets.index')}}" class="navb">DataSets</a>
	  <a href="{{url_for('training.index')}}" class="navb">Training</a>
	  <a href="{{url_for('testing.index')}}" class="navb">Testing</a>
	</div> 
      </div>
      <hr />


      <div id="main">
  	{% block content %}{% endblock %}
      </div>

      <div id="footer">	
	<hr />
	<div class="left">
	  <a href="https://github.com/Ranler/boostingPL">BoostingMR</a>, 2012
	</div>
      </div>	
    </div>
  </body>
</html>

boostingMR/templates/_sleft.html
<div id="sleft">
  <ul>
    <li><a href="{{url_for('frontend.dataset')}}">Step 1: dataset format</a></li>
    <li><a href="{{url_for('frontend.model')}}"> Step 2: model choose</a></li>
    <li><a href="{{url_for('frontend.test')}}">Step 3: test options</a></li>
  </ul>
</div>

boostingMR/templates/datasets/_upload.html
<div class="dbox">
  <h2>Upload new dataset</h2>
  <form method="post" id="" action="{{url_for('frontend.dataset_next')}}">
    <tr>
      Dataset format: 
      <select name="" id="">  
	<option value="1">ARFF</option>  
	<option value="2">CSV</option>  
	<option value="3">LightSVM</option>  
	<option value="4">other</option>  
      </select>
    </tr>
    
    <br />
    <input type="file" name="file" />
    
    <!-- ARFF -->
    <!-- CSV -->
    <!-- LightSVM -->
    <!-- user define -->
    <table>
      <tbody>
	<tr>
	  <td class="tleft">Separator:</td>
	  <td class="tright"><input type="text" name="" value="," /></td>
	</tr>
	<tr>
	  <td>Attributes Number:</td>
	  <td><input type="text" name="" value="" /></td>
	</tr>
	<tr>
	  <td>Class Index:</td>
	  <td><input type="text" name="" value="-1" />(-1 means the last index in line)</td>
	</tr>
	<tr>
	  <td>Classes:</td>
	  <td><input type="text" name="" value="+1,-1" />(separate with ',', such as "+1,-1")</td>
	</tr>
      </tbody>
    </table>   
    <input type="submit" value="upload"></input>
  </form>
</div>

boostingMR/templates/datasets/index.html
{% extends "_layout.html" %}

{% block content %}

<div id="dmain">

  <div class="dbox">
    <h2>All Datasets</h2>
    <table>
      <tbody>
	<tr>
	  <th>id</th>
	  <th>name</th>
	  <th>size</th>
	  <th>instances</th>
	  <th>classes</th>
	  <th>operation</th>
	</tr>
	<tr>
	  <td>1</td>
	  <td>dataset</td>
	  <td>1.4GB</td>
	  <td>1000000</td>
	  <td>2</td>
	  <td>
	    <button>generate new</button>
	    <button>details</button>
	    <button>delete</button>
	  </td>
	</tr>
      </tbody>
    </table>
  </div>

  <a href="{{url_for('datasets.upload')}}">Upload</a>

  <a href="{{url_for('datasets.random')}}">Random</a>

</div>

{% endblock %}

boostingMR/templates/datasets/random.html
{% extends "_layout.html" %}

{% block content %}

<div class="dbox">
  <h2>Random new dataset</h2>
  {% if msg %} <p><div class="msg"> {{ msg }} </div></p> {% endif %}

  <form method="post" id="" action="{{url_for('datasets.random')}}">
    <table>
      <tbody>
	<tr>
	  <td class="tleft">Dataset Name:</td>
	  <td class="tright"><input type="text" name="rdname" value="" /></td>
	</tr>
	<tr>
	  <td class="tleft">Data Generator:</td>
	  <td class="tright">
	    <select name="rdgen" id="">  
              <option value="1">RDG1</option>  
	    </select>
	  </td>
	</tr>
	<tr>
	  <td>Number of Attributes:</td>
	  <td><input type="text" name="rdnAttr" value="100" /></td>
	</tr>
	<tr>
	  <td>Number of Classes:</td>
	  <td><input type="text" name="rdnClass" value="2" /></td>
	</tr>
	<tr>
	  <td>Number of Instances:</td>
	  <td><input type="text" name="rdnInst" value="10000" /></td>
	</tr>
      </tbody>
    </table>     
    
    <br/>
    <input type="submit" value="create"/>
  </form>
</div>

{% endblock %}

boostingMR/templates/datasets/upload.html
{% extends "_layout.html" %}

{% block content %}
<div class="dbox">
  <h2>Upload new dataset</h2>
  <form method="post" id="" action="{{url_for('frontend.dataset_next')}}">
    <tr>
      Dataset format: 
      <select name="" id="">  
	<option value="1">ARFF</option>  
	<option value="2">CSV</option>  
	<option value="3">LightSVM</option>  
	<option value="4">other</option>  
      </select>
    </tr>
    
    <br />
    <input type="file" name="file" />
    
    <!-- ARFF -->
    <!-- CSV -->
    <!-- LightSVM -->
    <!-- user define -->
    <table>
      <tbody>
	<tr>
	  <td class="tleft">Separator:</td>
	  <td class="tright"><input type="text" name="" value="," /></td>
	</tr>
	<tr>
	  <td>Attributes Number:</td>
	  <td><input type="text" name="" value="" /></td>
	</tr>
	<tr>
	  <td>Class Index:</td>
	  <td><input type="text" name="" value="-1" />(-1 means the last index in line)</td>
	</tr>
	<tr>
	  <td>Classes:</td>
	  <td><input type="text" name="" value="+1,-1" />(separate with ',', such as "+1,-1")</td>
	</tr>
      </tbody>
    </table>   
    <input type="submit" value="upload"></input>
  </form>
</div>
{% endblock %}

boostingMR/templates/frontend.html
{% extends "_layout.html" %}

{% block content %}

<div id="">
  <h3>What is BoostingPL?</h3>

  <p>BoostingPL is a scalable and parallel machine learning tools for Boosting
  (What is Boosting? http://en.wikipedia.org/wiki/Boosting).</p>

  </p>This Project is based on this paper:</p>
 
      </p>Indranil Palit and Chandan K. Reddy, "Scalable and Parallel Boosting
      with MapReduce", IEEE Transactions on Knowledge and Data Engineering
      (TKDE), 2012.</p>
   
  <p>If you want to know the theory and demonstration of algorithms in BoostingPL
  , this paper provides references for further reading.</p>

  <p>The MapReduce platform we used is Apache Hadoop(http://hadoop.apache.org/)
  , which is an opensource project and is more popular than other 
  implementations of MapReduce. You can deploy it on Amazon EC2 or your own 
  cluster.</p>

  <p>The cgl-mapreduce version for BoostingPL is also vailable from the TKDE paper 
  authors, you can download "CGL-MapReduce-BoostingPL.zip" in "extra/" directory.
  This cgl-mapreduce version depends on these libraries: Weka, twister-0.8, 
  NaradaBrokering-4.2.2. You can download these from source websites.<p>


</div>

{% endblock %}

boostingMR/templates/testing/index.html
{% extends "_layout.html" %}

{% block content %}
{% include "_sleft.html" %}

<div id="smain">
  <h2>Step 3: Test options</h2>
  <form method="" id="" action="">
    <table>
      <tbody>
	<td>Use training set</td>
	<td>Cross-validation</td>
	<td>Rercentage split</td>
	<td>Supplied test set</td>
      </tbody>
    </table>
    <input type="submit" value="next"></input>
  </form>
</div>
{% endblock %}

boostingMR/templates/training/index.html
{% extends "_layout.html" %}

{% block content %}
{% include "_sleft.html" %}

<div id="smain">
  <h2>Step 2: Model Choose</h2>
  <form method="" id="" action="">
    <table>
      <tbody>
	<tr>
	  <td class="tleft">Boosting Model:</td>
	  <td class="tright">
	    <select name="" id="">  
              <option value="1">AdaBoostPL</option>  
              <option value="2">LogitBoostPL</option>  
	    </select>
	  </td>
	</tr>
	<tr>
	  <td>Parallel Number:</td>
	  <td><input type="text" name="" value="" /></td>
	</tr>
	<tr>
	  <td>Iteration Number:</td>
	  <td><input type="text" name="" value="" /></td>
	</tr>
	<tr>
	  <td>Weak Classifier:</td>
	  <td>
	    <select name="" id="">  
              <option value="1">DecisionStump</option>  
	    </select>  	    
	  </td>
	</tr>
      </tbody>
    </table>
    <input type="submit" value="next"></input>
  </form>
</div>
{% endblock %}